### ISSUE TITLE
multiple devices?

### ISSUE THREAD

**Issue by betyar** [jorijnsmit/onlineChecker#10]
Hi,

I am a little unclear about multiple config files. Does this mean I can have the script check for multiple devices at the same time? I tried to run the following command

> python $LOCATION/online_checker.py $LOCATION/config.ini $LOCATION/laptop.ini
 
but only the first config file is read. 

Can multiple devices be handled by the script in the first place? Do I have to run multiple instances of the script or is it possible to somehow list multiple devices within the config file?

Thanks in advance and great work by the way!

**Comment by betyar** [comment]
For now I solved my problem by simply running multiple instances of the script like so within a bash file:

> python $LOCATION/online_checker.py $LOCATION/config.ini &
> python $LOCATION/online_checker.py $LOCATION/laptop.ini &

Meanwhile I came across a code snippet which may be useful for integrating multiple devices within the script itself, something like the following using subprocess:

```
import sys
import subprocess

procs = []
for i in range(86):
    proc = subprocess.Popen([sys.executable, 'task.py', '{}ip(i)', '{}idx(i)'])
    procs.append(proc)

for proc in procs:
    proc.wait()

```
This snippet is just a sample, it won't work out of the box, nevertheless it's an idea which can be considered.

**Comment by jorijnsmit** [comment]
Yes you are right, currently the way to run multiple config files is to have several instances of the script running parallel.

Your subprocess suggestion is definitely a good one and could be implemented!

**Comment by Monoposto** [comment]
Just found your script today, got it to work, but now am strugling to get it running for multiple (>10) devices.. through systemctl.
Any advice would be much appreciated.. Thanks in advance!

**Comment by ebretteville** [comment]
+1 if we can add multiple config files as parameter of python online_checker.py config1.ini config2.ini configX.ini
