### ISSUE TITLE
install requests for python3

### ISSUE THREAD

**Issue by BurningTyre** [jorijnsmit/onlineChecker#13]
First of all, thank you very much for all the work done on this.

After installing it according the Readme it was working on the commandline but not when using it as a service. 

It was throwing an error about restarting the service too often and investigating more I came to line 9 of online_checker.py, where it says `import requests`

After some research on the internet i found the solution. 

In the readme you write that is needed `pip install requests` but that is requests for python not for python3. 

`apt-get install python3-requests` solved my problem.

**Comment by jorijnsmit** [comment]
Glad you like it!

The needed `pip` commands can vary across systems, depending on the already existing setup. For me it works for Python 3 but apparently not for you.

Thanks for posting a solution here, it might serve somebody else!
