### ISSUE TITLE
cant make this work :(

### ISSUE THREAD

**Issue by maximm07** [jorijnsmit/onlineChecker#4]
Hello..asking for some help..it should be easy to implement this, but for some reason script is failing on my system..if i run it manual or via the service..it that case the service fails...dependencies are installed..this is what i get running the script;

/domoticz/scripts/onlineChecker$ sudo python3 -u online_checker.py
Traceback (most recent call last):
  File "online_checker.py", line 88, in <module>
    infinite_loop()
  File "online_checker.py", line 75, in infinite_loop
    print(DEVICE+' went offline, waiting for it to come back...')
TypeError: unsupported operand type(s) for +: 'SectionProxy' and 'str'

I tripple checked the config.ini..:)

Using Python 3.6.7

**Comment by maximm07** [comment]
please ignore this..found the issue..:) IP needs to be present on the network when first running the script..i was running this when device was offline.

**Comment by jorijnsmit** [comment]
Actually you hit a nasty bug there! It's just that by your device being online the script skips that line and never hits the bug. Fixed now, thank you! Please don't forget to `git pull` to the newest version :-)

**Comment by maximm07** [comment]
Thanks for looking into this..i have another problem now..script works, but since i have 3 Iphones in the house ping its not usable..:(, when iphone screen goes off device is not responding to ping anymore..this is a common known behavior with iphones...
