### ISSUE TITLE
does not switch off

### ISSUE THREAD

**Issue by betyar** [jorijnsmit/onlineChecker#6]
After a relatively easy install and first test, I have run into some nasty bumps. When I first tried it out the virtual switch turned on after a few seconds. Excellent. However, after further testing things didn't go so well. I disconnected my phone from the WiFi but the switch remained on (I waited over five minutes). After manually switching it off and then reconnecting my phone to the WiFi, it wouldn't switch on. I killed the script and tried again. Once more, the switch would go on but afterward it failed to detect whether my phone was online or not. Thus, it appears to only work when the script is first run; after nothing happens. 

I am running the script in the background from the command line on my Synology NAS. My phone OS is Android. I tried going online with my phone immediately after I started the script as well as waiting a minute or two; in all cases, the switch went on after a few seconds. Afterward, it would neither go on or off when I changed my online status.

As I mentioned elsewhere, I was always able to arping my phone from the command line; a regular ping doesn't work.

Any ideas where the problem might be?

**Comment by cahir1987** [comment]
I have the same problem.

some solution?

**Comment by betyar** [comment]
Nope. Still trying.
